project:
  type: website
  output-dir: docs

website:
  title: "Felicia Akinde"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Visualization
        menu:
          - text: "Project 1: Coffee Style by Age"
            href: coffee_survey.html
          - text: "Project 1: Cheese Color by Animal"
            href: cheese.html
          - text: "Project 2: Summer Movie Ratings"
            href: project2.html
          - text: "Project 3: Deck of Cards Simulation"
            href: deck_of_cards.html
          - text: "Project 4: WAI Database Analysis Using SQL"
            href: WAI_database.html
format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page_layout: full

editor: visual

