project:
  type: website
  output-dir: docs

website:
  title: "Felicia Akinde"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Visualization
        menu:
          - text: "Coffee Survey"
            href: coffee_survey.html
          - text: "Cheese"
            href: cheese.html
          - text: "Mini Project 2"
            href: project2.html
          - text: "Mini Project 3"
            href: deck_of_cards.html
format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page_layout: full

editor: visual

